fix: enhance debug logging in initialization script

diff --git a/oh-shit/resolve-conflict/.init b/oh-shit/resolve-conflict/.init
--- a/oh-shit/resolve-conflict/.init
+++ b/oh-shit/resolve-conflict/.init
@@ -7,10 +7,18 @@ chmod +x /challenge/submit
 
 export PATH="/run/dojo/bin:$PATH"
 
-touch debug.log # DEBUG USE ONLY
-echo "The location of sudo is: $(which sudo)" > debug.log
-echo "The location of bash is: $(which bash)" >> debug.log
-echo "The location of git is: $(which git)" >> debug.log
+touch debug0.log # DEBUG USE ONLY
+echo `whoami` > debug0.log
+echo "The location of sudo is: $(which sudo)" >> debug0.log
+echo "The location of bash is: $(which bash)" >> debug0.log
+echo "The location of git is: $(which git)" >> debug0.log
+
+# check if sudo exists
+if ! command -v sudo &> /dev/null
+then
+    echo "sudo could not be found" >> debug0.log
+    exit 1
+fi
 
 sudo -u hacker bash <<'EOF'
 
